### ISSUE TITLE
[bug] parseMessageStream 로직이 바뀐듯여

### ISSUE THREAD

**Issue by anso33** [42Blank/ft_irc#11]
parseMessageStream 와 parseWelcomeMessageStream의 로직이 바뀐거 아님감요?
그래서 command땡떙떙 종류의 함수들이 동작하지 않는 결과가 있었답니다. 그래서 제 브랜치에는 바꿔놨는데 이것을 지금 머지할까요 아님 나중에 할까요? 

확인한번 해보고 말해주삼요

와ㅏㅏㅏ 나도 드디어 이슈등록해봤따ㅏㅏ

**Comment by ft-jasong** [comment]
parseMessageStream 멤버함수는 연결된 client들의 message stream을 parsing하는 것에 쓸 것 같아요. 정확히는 @chichoon 이 결정할테지만..! 현재 작업물 개인 브랜치에 푸시하시고 알려주시면 코드 확인해보겠습니다!

**Comment by chichoon** [comment]
이거 아예 수정하고있습니다 아까 허들로설명한부분을 적용하려면 구조를 다시 바궈야하더라구요 ㅠ

**Comment by anso33** [comment]
아하 근데 그럼 받아온 메세지 파싱은 계속 parseMessageStream 이 위치하던 쪽에서 해서 parameter 로 전달해주도록 되어 있나유?

**Comment by chichoon** [comment]
parseWelcomeMessageStream은 지금 메인에 올라간 상태가 맞아요
해당 명령어들은 웰컴때만 사용되기때문이죵
그외 join같이 로그인후에만 사용할수있는 명령어들운 parseMessageStream에 넣는게 맞습니다
근데 어차피 구조 갈아엎는중이라 지금은 의미없어요 ㅠ

**Comment by anso33** [comment]
아 이건 무순말인지 알았어요 다른 command 들은 parseMessageStream 여기서 if 로 전달하도록 하면 되죵?

**Comment by chichoon** [comment]
parseWelcome -> PASS USER NICK
parseMessage -> 그외명령어들

이렇게생각해주세욤
근데 지금 다시 두개 합치는중,,,, ㅎ 일단 따로작업해주시면 충돌해결할때 제가 수정할게요

**Comment by chichoon** [comment]
@anso33 내내네 마지막댓이 정확해요!!!

**Comment by anso33** [comment]
옼에 알게숩니다. 이해 완료
