### ISSUE TITLE
[Fix] nc 커맨드 비정상 작동 확인하기

### ISSUE THREAD

**Issue by chichoon** [42Blank/ft_irc#16]
- 자고싶어서 일단 TODO 백로그로 작성
- nc 커맨드가 ctrl+c 누르기 전까지 메시지가 하나도 안 감
- DALnet 같은 경우 엔터 누를 때마다 전송되어야 함
- irssi는 문제 없는듯??

**Comment by ft-jasong** [comment]
막 디버깅을 하던 도중, netcat의 처리 방식을 어느정도 알게 된 것 같아서 커멘트 남깁니다.
1. netcat은 입력 스트림을 그냥 개행기준으로 처리하는 듯 합니다.
2. 우리의 서버는 CRLF가 안들어오면 무조건 무시합니다.
결론 -> crlf가 안들어와서 그냥 무한루프가 돌고있습니다. concat하는 부분에서 말이죠.

이따 오시면 저와 같이 예제 코드 봅시다. 껄껄

**Comment by chichoon** [comment]
오노 이런일이
개행기준으로 CRLF 따박따박 넣어주는줄알앗군요

**Comment by anso33** [comment]
이거 해결
