### ISSUE TITLE
[Fix] User의 hostname이 사라지는 버그

### ISSUE THREAD

**Issue by ft-jasong** [42Blank/ft_irc#19]
Server.cpp의 sendClientMessage2함수에서 user.gethostname() 호출 시, hostname이 공백으로 나오는 버그가 있습니다.

제가 해볼게요 !

**Comment by ft-jasong** [comment]
User 클래스의 대입 연산자 오버로딩에서 hostname을 복사하는 부분이 빠진 것을 확인했습니다. 다음 커밋에 올리도록 하겠습니다.

**Comment by anso33** [comment]
wow 자송은 신이야
