### ISSUE TITLE
[FEAT] command 완성하기

### ISSUE THREAD

**Issue by ft-jasong** [42Blank/ft_irc#23]
- [x] join
- [x] who
- [x] kick
- [x] names
- [x] mode
- [x] topic
- [x] PRIVMSG
- [x] part

**Comment by chichoon** [comment]
저 QUIT 하고있음

**Comment by chichoon** [comment]
WHO도 내가할게요

**Comment by anso33** [comment]
저 /part 먼저 할게요

**Comment by anso33** [comment]
여기서 3개만 더 완성하면 명령어는 다 한걸까요? 저는 (kick과) mode를 목요일에 해볼까 합니다.

**Comment by chichoon** [comment]
who 끝

**Comment by chichoon** [comment]
모드 잘 동작하는거아닌가야ㅕ?? 이슈 닫아도댈듯??
