### ISSUE TITLE
🐞BUG : 모든 User가 같은 주소를 사용함

### ISSUE THREAD

**Issue by ft-jasong** [42Blank/ft_irc#3]
Server::receiveClientMessage 에서 User 클래스 변수가 while문 밖에 있어서 같은 주소값을 참조합니다 ! 새로운 User가 들어왔을때 같은 주소값을 사용해서 전부 바뀌게 되네요!!!

**Comment by chichoon** [comment]
왓더뻑

**Comment by chichoon** [comment]
이것은 자송이 이야기해준 방식 (벡터에 깊은복사 사용하기) 으로 바꿔볼게요

**Comment by ft-jasong** [comment]
reference형식으로 변경, 이슈 닫겠습니다.
