### ISSUE TITLE
[fix] 채널 입장시 채팅인원이 올바르게 보이지 않는 버그

### ISSUE THREAD

**Issue by ft-jasong** [42Blank/ft_irc#37]
ex) channel operator가 oper, 일반 채팅자가 User라고 하면
operator 화면
[@oper]
User화면
[@user]
이렇게 뜹니다~ 확인해서 fix 해야할 것 같아요 !!!

**Comment by chichoon** [comment]
<img width="729" alt="스크린샷 2023-01-05 오후 10 23 58" src="https://user-images.githubusercontent.com/37893979/210790114-deab7d6e-1d3f-4e85-9ba3-e9962e42001f.png">

사실 고치고 있었어요
고치다가 화장실감
