### ISSUE TITLE
[BUG] container overflow

### ISSUE THREAD

**Issue by chichoon** [42Blank/ft_irc#38]
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/37893979/210811241-a1bd290e-b53e-4af8-85a5-3446c046ba37.png">

- 재현 방법: 모름
- 두 명이 동시에 같은 채널에 접속한 뒤, 한 명이 quit으로 접속을 끊어버리고 조금 기다리니 발생했습니다

**Comment by ft-jasong** [comment]
index 부분 그냥 clientFd바로 넣는거로 수정해서 해결했습니다. 이슈 닫겠습니다
